# Requires
fastlane_require 'yaml'

fastlane_version '2.134.0'

skip_docs

default_platform(:ios)

platform :ios do

  desc 'Upload a developer build to Firebase.'
  lane :develop do
    app_id = '1:899824677417:ios:72ea335f3c6ab1d58fa238';

    build_number = number_of_commits()

    disable_automatic_code_signing

    # Build app with Flutter toolchain
    Dir.chdir('../..') do
      sh('flutter', 'packages', 'get')
      sh('flutter', 'clean')
      sh('flutter', 'build', 'ios', '--release', '--no-codesign', "--build-number=#{build_number}")
    end

    update_info_plist(
      plist_path: 'Runner/Info.plist',
      display_name: 'SoundPlayer'
    )

    # Build ipa file
    build_ios_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: 'development',
    )

    # Upload to Firebase
    # firebase appdistribution:distribute ../Runner.ipa --app 1:899824677417:ios:72ea335f3c6ab1d58fa238
    sh('firebase', 'appdistribution:distribute', '../Runner.ipa', "--app=#{app_id}")

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts
  end

  ################################################
  #
  #################### HELPERS ##################
  #
  ################################################

  desc 'Returns a default changelog.'
  lane :default_changelog do
    changelog = changelog_from_git_commits(
        between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || "HEAD^^^^^", "HEAD"],
        pretty: "- %s"
    )
    # HAX: strip emoji from changelog
    changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
    Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
    puts changelog
    changelog
  end

  desc 'Get certificates and register devices.'
  lane :certificates do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(git_url: "https://github.com/data-hfg/fernarzt-certificates",
          app_identifier: ["me.minikin.firebase.alpha"],
          force_for_new_devices: true)
  end

end
