#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/oleksandr_prokhorenko/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/oleksandr_prokhorenko/Development/GitHub/soundcloud_audio_player"
export "FLUTTER_TARGET=/Users/oleksandr_prokhorenko/Development/GitHub/soundcloud_audio_player/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/oleksandr_prokhorenko/dev/flutter/bin/cache/artifacts/engine/ios-release"
export "FLUTTER_BUILD_NAME=0.0.8"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
